### ISSUE TITLE
NGINX setup with https

### ISSUE THREAD

**Issue by pheyvaer** [peta-pico/nanopub-services#1]
Hi,

If we want to run the services behind an NGINX and enable https, what do we write in https://github.com/peta-pico/nanopub-services/blob/master/docker-compose.override.yml.template?
```
version: '2'
services:
  server:
    environment:
      - NPS_PUBLIC_URL=http://server.np.YOUR.SERVER.DOMAIN/
  ldf:
    environment:
      - BASEURL=http://ldf.np.YOUR.SERVER.DOMAIN/
  grlc:
    environment:
      - GRLC_SERVER_NAME=grlc.np.YOUR.SERVER.DOMAIN
```
Do we put `http` or `https` in `environment`? For `server` this seems to work with `https`, but for `ldf` I get a 502. But I'm not 100% sure whether the 502 is related to `http` vs `https`.
